# Continue integrate project to Aliyun

name: CI-Aliyun

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: ng build --prod --baseHref /bitmap/ --deployUrl /bitmap/
        
      - name: Deploy to Aliyu
        uses: hengkx/ssh-deploy@v1.0.1
        env:
          HOST: ${{ secrets.ALIYUN_HOST }}
          USERNAME: ${{ secrets.ALIYUN_USER }}
          PASSWORD: ${{ secrets.ALIYUN_PWD }}
          PORT: 22
          SOURCE: 'dist/'
          TARGET: ${{ secrets.ALIYUN_DEPLOY_DEST_PATH }}
