# Continue integrate project to Aliyun

name: CI-Aliyun

on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: npm install and build
        run: |
          npm install
          npm run build

      # - name: Deploy to Aliyun server
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      #     ARGS: "-avz --delete"
      #     SOURCE: "dist/"
      #     REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
      #     REMOTE_USER: ${{ secrets.ALIYUN_USER }}
      #     TARGET: ${{ secrets.ALIYUN_DEPLOY_DEST_PATH }}
      - name: deploy
        id: funny-deploy
        uses: BoatNg/funny-deploy@master
        env:
          REMOTE_HOST: '${{ secrets.ALIYUN_HOST }}'
          REMOTE_USER: '${{ secrets.ALIYUN_USER }}'
          REMOTE_PASSWORD: '${{ secrets.PWD }}'
          REMOTE_PATH: ${{ secrets.ALIYUN_DEPLOY_DEST_PATH }}
          SOURCE: 'dist/'
